#!/usr/bin/env python3
"""Create translated dermatologist audiences and draft campaigns in Listmonk."""
import base64, json, os, paramiko
from pathlib import Path

COUNTRIES = [x["country"] for x in json.loads(Path("listmonk_emails/.dermatologist_country_inventory.json").read_text(encoding="utf-8"))]
SPECIAL = {
"Spanish": {'Andorra','Argentina','Bolivia','Chile','Colombia','Costa Rica','Dominican Republic','Ecuador','El Salvador','Honduras','Mexico','Panama','Paraguay','Peru','Spain','Uruguay'},
"Portuguese": {'Brazil','Macao','Portugal','Timor Leste'},
"French": {'France','French Guiana','French Polynesia','French Southern Territories','Guadeloupe','Martinique','Monaco','Saint Barthelemy','Saint Martin','Saint Pierre and Miquelon'},
"German": {'Austria','Germany','Liechtenstein','Switzerland'},
"Italian": {'Italy','San Marino','Vatican'},
"Dutch": {'Aruba','Belgium','Bonaire, Saint Eustatius and Saba','Sint Maarten','Suriname','The Netherlands'},
"Greek": {'Cyprus','Greece'}, "Polish": {'Poland'}, "Romanian": {'Moldova','Romania'},
"Czech": {'Czechia'}, "Slovak": {'Slovakia'}, "Hungarian": {'Hungary'},
"Croatian": {'Croatia','Montenegro','Serbia','Slovenia'}, "Bulgarian": {'Bulgaria','North Macedonia'},
"Arabic": {'Bahrain','Kuwait','Oman','Qatar','Saudi Arabia','United Arab Emirates'},
"Russian": {'Armenia','Azerbaijan','Georgia','Mongolia'}, "Albanian": {'Albania'},
}

T = {
"English": ["Dear Dermatologist,","I was looking through Google Maps for dermatology clinics in the area and came across your practice, so I thought I’d reach out.","We’re a software development company, and this is just a very brief introduction to two solutions we offer for dermatology clinics:","Dermatology Websites","Rebranding or redesigning your existing website to give your clinic a more modern and professional online presence. AI is changing the game in web design, and some of the new designs and possibilities are absolutely stunning.","Dermatology CRM Software","A simple system to manage patient enquiries, follow-ups and appointments in one place.","You can have a quick look at both solutions here:","If it looks relevant to your clinic, I’d be happy to have a quick chat.","Kind regards","Dermatology websites and CRM software"],
"Spanish": ["Estimado/a dermatólogo/a:","Estaba buscando clínicas dermatológicas de la zona en Google Maps y encontré su consulta, así que pensé en ponerme en contacto con usted.","Somos una empresa de desarrollo de software y esta es una presentación muy breve de dos soluciones que ofrecemos para clínicas dermatológicas:","Páginas web para dermatología","Renovamos o rediseñamos su página web para dar a su clínica una presencia digital más moderna y profesional. La IA está transformando el diseño web y algunas de las nuevas posibilidades son realmente impresionantes.","Software CRM para dermatología","Un sistema sencillo para gestionar consultas de pacientes, seguimientos y citas en un solo lugar.","Puede ver rápidamente ambas soluciones aquí:","Si considera que puede ser relevante para su clínica, estaré encantado de mantener una breve conversación.","Un cordial saludo","Páginas web y software CRM para clínicas dermatológicas"],
"Portuguese": ["Caro(a) Dermatologista,","Estava a pesquisar clínicas dermatológicas na região através do Google Maps e encontrei a sua clínica, por isso decidi entrar em contacto.","Somos uma empresa de desenvolvimento de software e esta é apenas uma breve apresentação de duas soluções que oferecemos para clínicas dermatológicas:","Websites para Dermatologia","Fazemos o rebranding ou redesenho do seu website para proporcionar à clínica uma presença online mais moderna e profissional. A IA está a transformar o web design e algumas das novas possibilidades são verdadeiramente impressionantes.","Software CRM para Dermatologia","Um sistema simples para gerir pedidos de pacientes, acompanhamentos e consultas num único lugar.","Pode conhecer rapidamente ambas as soluções aqui:","Se considerar relevante para a sua clínica, terei todo o gosto em conversar brevemente consigo.","Com os melhores cumprimentos","Websites e software CRM para clínicas dermatológicas"],
"French": ["Cher/Chère dermatologue,","En recherchant des cliniques dermatologiques dans la région sur Google Maps, j’ai découvert votre cabinet et j’ai souhaité vous contacter.","Nous sommes une société de développement logiciel et voici une très brève présentation de deux solutions que nous proposons aux cliniques dermatologiques :","Sites web pour cabinets de dermatologie","Nous modernisons ou repensons votre site actuel afin d’offrir à votre clinique une présence en ligne plus professionnelle. L’IA transforme la conception web et ouvre des possibilités particulièrement impressionnantes.","Logiciel CRM pour la dermatologie","Un système simple pour gérer au même endroit les demandes des patients, les relances et les rendez-vous.","Vous pouvez découvrir rapidement les deux solutions ici :","Si cela vous semble pertinent pour votre clinique, je serais heureux d’échanger brièvement avec vous.","Bien cordialement","Sites web et logiciel CRM pour cliniques dermatologiques"],
"German": ["Sehr geehrte Dermatologin, sehr geehrter Dermatologe,","Bei der Suche nach dermatologischen Praxen in Ihrer Region auf Google Maps bin ich auf Ihre Praxis gestoßen und möchte mich deshalb kurz bei Ihnen melden.","Wir sind ein Softwareentwicklungsunternehmen. Mit dieser kurzen Nachricht möchte ich Ihnen zwei Lösungen für dermatologische Praxen vorstellen:","Websites für dermatologische Praxen","Wir modernisieren oder gestalten Ihre bestehende Website neu, damit Ihre Praxis online professioneller und zeitgemäßer auftritt. KI verändert das Webdesign grundlegend und ermöglicht beeindruckende neue Gestaltungsmöglichkeiten.","CRM-Software für Dermatologie","Ein einfaches System, mit dem Patientenanfragen, Nachfassaktionen und Termine zentral verwaltet werden können.","Einen kurzen Überblick über beide Lösungen finden Sie hier:","Wenn dies für Ihre Praxis interessant ist, freue ich mich über ein kurzes Gespräch.","Mit freundlichen Grüßen","Websites und CRM-Software für dermatologische Praxen"],
"Italian": ["Gentile Dermatologo/a,","Stavo cercando su Google Maps delle cliniche dermatologiche nella zona e ho trovato il suo studio, perciò ho pensato di contattarla.","Siamo una società di sviluppo software e questa è una breve presentazione di due soluzioni che offriamo alle cliniche dermatologiche:","Siti web per la dermatologia","Rinnoviamo o riprogettiamo il sito esistente per offrire alla clinica una presenza online più moderna e professionale. L’IA sta trasformando il web design e alcune delle nuove possibilità sono davvero straordinarie.","Software CRM per la dermatologia","Un sistema semplice per gestire in un unico luogo richieste dei pazienti, follow-up e appuntamenti.","Può vedere rapidamente entrambe le soluzioni qui:","Se ritiene che possa essere utile per la sua clinica, sarò lieto di parlarne brevemente.","Cordiali saluti","Siti web e software CRM per cliniche dermatologiche"],
"Dutch": ["Geachte dermatoloog,","Tijdens een zoektocht naar dermatologieklinieken in de regio via Google Maps kwam ik uw praktijk tegen. Daarom neem ik graag kort contact met u op.","Wij zijn een softwareontwikkelingsbedrijf. Hieronder vindt u een korte introductie van twee oplossingen die wij voor dermatologieklinieken aanbieden:","Websites voor dermatologieklinieken","Wij vernieuwen of herontwerpen uw bestaande website om uw kliniek een modernere en professionelere online uitstraling te geven. AI verandert webdesign ingrijpend en biedt indrukwekkende nieuwe mogelijkheden.","CRM-software voor dermatologie","Een eenvoudig systeem om patiëntaanvragen, opvolging en afspraken op één plek te beheren.","U kunt beide oplossingen hier kort bekijken:","Als dit relevant lijkt voor uw kliniek, maak ik graag tijd voor een kort gesprek.","Met vriendelijke groet","Websites en CRM-software voor dermatologieklinieken"],
"Greek": ["Αγαπητέ/ή Δερματολόγε,","Αναζητώντας δερματολογικές κλινικές στην περιοχή μέσω του Google Maps, βρήκα το ιατρείο σας και σκέφτηκα να επικοινωνήσω μαζί σας.","Είμαστε εταιρεία ανάπτυξης λογισμικού και θα θέλαμε να σας παρουσιάσουμε πολύ σύντομα δύο λύσεις για δερματολογικές κλινικές:","Ιστοσελίδες Δερματολογίας","Ανανεώνουμε ή επανασχεδιάζουμε την υπάρχουσα ιστοσελίδα σας, προσφέροντας στο ιατρείο μια πιο σύγχρονη και επαγγελματική διαδικτυακή παρουσία. Η τεχνητή νοημοσύνη αλλάζει τον σχεδιασμό ιστοσελίδων και δημιουργεί εντυπωσιακές νέες δυνατότητες.","Λογισμικό CRM Δερματολογίας","Ένα απλό σύστημα για τη διαχείριση αιτημάτων ασθενών, επακόλουθων ενεργειών και ραντεβού σε ένα μέρος.","Μπορείτε να δείτε γρήγορα και τις δύο λύσεις εδώ:","Εάν σας φαίνεται σχετικό με το ιατρείο σας, θα χαρώ να συζητήσουμε σύντομα.","Με εκτίμηση","Ιστοσελίδες και λογισμικό CRM για δερματολογικές κλινικές"],
"Polish": ["Szanowni Państwo,","Podczas wyszukiwania klinik dermatologicznych w okolicy w Google Maps natrafiłem na Państwa placówkę i postanowiłem się skontaktować.","Jesteśmy firmą tworzącą oprogramowanie. Chciałbym krótko przedstawić dwa rozwiązania dla klinik dermatologicznych:","Strony internetowe dla dermatologii","Odświeżamy lub przeprojektowujemy istniejącą stronę, aby klinika zyskała nowoczesny i profesjonalny wizerunek online. Sztuczna inteligencja zmienia projektowanie stron i otwiera niezwykle ciekawe możliwości.","Oprogramowanie CRM dla dermatologii","Prosty system do zarządzania zapytaniami pacjentów, kontaktami uzupełniającymi i wizytami w jednym miejscu.","Oba rozwiązania można szybko zobaczyć tutaj:","Jeśli rozwiązania mogą być przydatne dla Państwa kliniki, chętnie porozmawiam.","Z poważaniem","Strony internetowe i CRM dla klinik dermatologicznych"],
"Romanian": ["Stimate medic dermatolog,","Căutând clinici dermatologice din zonă pe Google Maps, am găsit cabinetul dumneavoastră și m-am gândit să vă contactez.","Suntem o companie de dezvoltare software, iar aceasta este o scurtă prezentare a două soluții pe care le oferim clinicilor dermatologice:","Site-uri web pentru dermatologie","Modernizăm sau reproiectăm site-ul existent pentru a oferi clinicii o prezență online mai modernă și profesională. Inteligența artificială schimbă designul web și oferă posibilități noi impresionante.","Software CRM pentru dermatologie","Un sistem simplu pentru gestionarea solicitărilor pacienților, urmăririlor și programărilor într-un singur loc.","Puteți vedea rapid ambele soluții aici:","Dacă vi se pare relevant pentru clinică, aș discuta cu plăcere pe scurt.","Cu stimă","Site-uri web și software CRM pentru clinici dermatologice"],
"Czech": ["Vážená paní doktorko, vážený pane doktore,","Při hledání dermatologických klinik ve vašem okolí na Google Maps jsem narazil na vaši ordinaci, a proto jsem se rozhodl vás oslovit.","Jsme společnost zabývající se vývojem softwaru a rádi bychom stručně představili dvě řešení pro dermatologické kliniky:","Webové stránky pro dermatologii","Modernizujeme nebo přepracujeme vaše stávající stránky, aby klinika získala modernější a profesionálnější online prezentaci. Umělá inteligence mění webdesign a přináší působivé nové možnosti.","CRM software pro dermatologii","Jednoduchý systém pro správu dotazů pacientů, následné komunikace a termínů na jednom místě.","Obě řešení si můžete rychle prohlédnout zde:","Pokud je to pro vaši kliniku relevantní, rád si s vámi krátce promluvím.","S pozdravem","Webové stránky a CRM pro dermatologické kliniky"],
"Slovak": ["Vážená pani doktorka, vážený pán doktor,","Pri hľadaní dermatologických kliník vo vašom okolí na Google Maps som našiel vašu ambulanciu, preto som sa rozhodol vás osloviť.","Sme spoločnosť zaoberajúca sa vývojom softvéru a radi by sme stručne predstavili dve riešenia pre dermatologické kliniky:","Webové stránky pre dermatológiu","Modernizujeme alebo prepracujeme vašu existujúcu stránku, aby klinika získala modernejšiu a profesionálnejšiu online prezentáciu. Umelá inteligencia mení webdizajn a prináša pôsobivé nové možnosti.","CRM softvér pre dermatológiu","Jednoduchý systém na správu otázok pacientov, následnej komunikácie a termínov na jednom mieste.","Obe riešenia si môžete rýchlo pozrieť tu:","Ak je to pre vašu kliniku relevantné, rád sa s vami krátko porozprávam.","S pozdravom","Webové stránky a CRM pre dermatologické kliniky"],
"Hungarian": ["Tisztelt Bőrgyógyász!","A Google Térképen a környék bőrgyógyászati klinikáit kerestem, és rátaláltam az Ön rendelőjére, ezért szerettem volna kapcsolatba lépni.","Szoftverfejlesztő vállalat vagyunk, és röviden szeretnénk bemutatni két megoldást bőrgyógyászati klinikák számára:","Bőrgyógyászati weboldalak","Megújítjuk vagy újratervezzük meglévő weboldalát, hogy klinikája modernebb és professzionálisabb online megjelenést kapjon. A mesterséges intelligencia átalakítja a webdesignt, és lenyűgöző új lehetőségeket kínál.","Bőrgyógyászati CRM szoftver","Egyszerű rendszer a páciensmegkeresések, utánkövetések és időpontok egy helyen történő kezelésére.","Mindkét megoldást röviden megtekintheti itt:","Ha ez releváns lehet klinikája számára, örömmel beszélgetek Önnel röviden.","Üdvözlettel","Weboldalak és CRM szoftver bőrgyógyászati klinikáknak"],
"Croatian": ["Poštovani dermatologu,","Pretražujući dermatološke klinike u vašem području na Google Mapsu, naišao sam na vašu ordinaciju pa sam vam se odlučio javiti.","Tvrtka smo za razvoj softvera i želimo ukratko predstaviti dva rješenja koja nudimo dermatološkim klinikama:","Web-stranice za dermatologiju","Obnavljamo ili redizajniramo postojeću web-stranicu kako bi vaša klinika imala moderniju i profesionalniju internetsku prisutnost. Umjetna inteligencija mijenja web-dizajn i donosi iznimne nove mogućnosti.","CRM softver za dermatologiju","Jednostavan sustav za upravljanje upitima pacijenata, naknadnom komunikacijom i terminima na jednom mjestu.","Oba rješenja možete brzo pogledati ovdje:","Ako je ovo relevantno za vašu kliniku, rado bih kratko razgovarao s vama.","Srdačan pozdrav","Web-stranice i CRM za dermatološke klinike"],
"Bulgarian": ["Уважаеми дерматолог,","Докато търсех дерматологични клиники във вашия район в Google Maps, попаднах на вашата практика и реших да се свържа с вас.","Ние сме компания за разработка на софтуер и бихме искали накратко да представим две решения за дерматологични клиники:","Уебсайтове за дерматология","Обновяваме или преработваме съществуващия ви уебсайт, за да осигурим по-модерно и професионално онлайн присъствие. Изкуственият интелект променя уеб дизайна и предлага впечатляващи нови възможности.","CRM софтуер за дерматология","Лесна система за управление на запитвания от пациенти, последваща комуникация и часове на едно място.","Можете да разгледате накратко и двете решения тук:","Ако това е подходящо за вашата клиника, с удоволствие бих провел кратък разговор.","С уважение","Уебсайтове и CRM за дерматологични клиники"],
"Arabic": ["حضرة طبيب/طبيبة الأمراض الجلدية المحترم/ة،","أثناء بحثي في خرائط Google عن عيادات الأمراض الجلدية في المنطقة، وجدت عيادتكم ولذلك رغبت في التواصل معكم.","نحن شركة لتطوير البرمجيات، وهذه مقدمة قصيرة جدًا عن حلّين نقدمهما لعيادات الأمراض الجلدية:","مواقع إلكترونية لعيادات الجلدية","نقوم بتحديث أو إعادة تصميم موقعكم الحالي لمنح العيادة حضورًا رقميًا أكثر حداثة واحترافية. يغيّر الذكاء الاصطناعي عالم تصميم المواقع ويفتح إمكانات جديدة ومميزة.","برنامج CRM لعيادات الجلدية","نظام بسيط لإدارة استفسارات المرضى والمتابعة والمواعيد في مكان واحد.","يمكنكم الاطلاع سريعًا على الحلّين هنا:","إذا كان ذلك مناسبًا لعيادتكم، فسيسعدني إجراء محادثة قصيرة معكم.","مع أطيب التحيات","مواقع وبرامج CRM لعيادات الأمراض الجلدية"],
"Russian": ["Уважаемый врач-дерматолог!","Во время поиска дерматологических клиник в вашем районе на Google Maps я увидел вашу клинику и решил связаться с вами.","Мы занимаемся разработкой программного обеспечения и хотели бы кратко представить два решения для дерматологических клиник:","Сайты для дерматологических клиник","Мы обновляем или полностью перерабатываем существующий сайт, чтобы обеспечить клинике более современное и профессиональное присутствие в интернете. Искусственный интеллект меняет веб-дизайн и открывает впечатляющие новые возможности.","CRM для дерматологии","Простая система для управления обращениями пациентов, последующими контактами и записями на приём в одном месте.","Кратко ознакомиться с обоими решениями можно здесь:","Если это актуально для вашей клиники, буду рад коротко обсудить детали.","С уважением","Сайты и CRM для дерматологических клиник"],
"Albanian": ["I nderuar dermatolog,","Duke kërkuar klinika dermatologjike në zonën tuaj në Google Maps, gjeta klinikën tuaj dhe mendova t’ju kontaktoja.","Jemi një kompani zhvillimi softuerësh dhe kjo është një prezantim shumë i shkurtër i dy zgjidhjeve që ofrojmë për klinikat dermatologjike:","Faqe interneti për dermatologji","Rifreskojmë ose ridizajnojmë faqen ekzistuese për t’i dhënë klinikës një prani online më moderne dhe profesionale. Inteligjenca artificiale po ndryshon dizajnin e faqeve dhe po sjell mundësi të reja mbresëlënëse.","Softuer CRM për dermatologji","Një sistem i thjeshtë për menaxhimin e kërkesave të pacientëve, ndjekjeve dhe takimeve në një vend.","Të dyja zgjidhjet mund t’i shihni shkurtimisht këtu:","Nëse ju duket e përshtatshme për klinikën tuaj, do të isha i lumtur të bisedonim shkurt.","Me respekt","Faqe interneti dhe CRM për klinikat dermatologjike"],
}

def html(v, lang):
    body=f'''<p>{v[0]}</p><p>{v[1]}</p><p>{v[2]}</p><p><strong>1. {v[3]}</strong> – {v[4]}</p><p><strong>2. {v[5]}</strong> – {v[6]}</p><p>{v[7]}<br><a href="https://consthruads.com/dermatology/?lang=en" target="_blank" rel="noopener noreferrer">https://consthruads.com/dermatology/?lang=en</a></p><p>{v[8]}</p><p>{v[9]},<br>Edward</p>'''
    return f'<div dir="rtl">{body}</div>' if lang=="Arabic" else body

def q(s): return "'"+s.replace("'","''")+"'"

assigned={}; groups={k:[] for k in T}
for c in COUNTRIES:
    matches=[lang for lang,cs in SPECIAL.items() if c in cs]
    if len(matches)>1: raise RuntimeError(f"Duplicate mapping {c}: {matches}")
    lang=matches[0] if matches else "English"; assigned[c]=lang; groups[lang].append(c)
if len(assigned)!=119 or set(assigned)!=set(COUNTRIES): raise RuntimeError("Country mapping incomplete")

mapping=[]
for lang,countries in groups.items():
    for c in countries:
        display="USA" if c=="United States" else c
        mapping.append((lang,f"{display} dermatologist leads *"))

mapping_values=",".join(f"({q(a)},{q(b)})" for a,b in mapping)
defs=[]
for lang,v in T.items():
    slug=lang.lower(); defs.append((lang,f"dermatologist {slug} language **",f"Dermatology Solutions - {lang}",v[10],html(v,lang)))
defs_values=",".join(f"({q(a)},{q(b)},{q(c)},{q(d)},{q(e)})" for a,b,c,d,e in defs)

sql=f'''\\set ON_ERROR_STOP on
BEGIN; SELECT pg_advisory_xact_lock(88110001);
CREATE TEMP TABLE lang_map(language text,list_name text); INSERT INTO lang_map VALUES {mapping_values};
CREATE TEMP TABLE lang_defs(language text,group_name text,campaign_name text,subject text,body text); INSERT INTO lang_defs VALUES {defs_values};
DO $$ BEGIN IF (SELECT COUNT(*) FROM lang_map)<>119 OR (SELECT COUNT(DISTINCT list_name) FROM lang_map)<>119 THEN RAISE EXCEPTION 'Language map invalid'; END IF; IF (SELECT COUNT(*) FROM lists l JOIN lang_map m ON m.list_name=l.name)<>119 THEN RAISE EXCEPTION 'Source lists missing'; END IF; END $$;
INSERT INTO lists(uuid,name,type,optin,tags,description) SELECT gen_random_uuid(),d.group_name,'private','single',ARRAY[]::varchar[],'Strict bounce-filtered multilingual dermatologist audience: '||d.language FROM lang_defs d WHERE NOT EXISTS(SELECT 1 FROM lists l WHERE l.name=d.group_name);
CREATE TEMP TABLE eligible AS SELECT DISTINCT d.language,s.id subscriber_id FROM lang_defs d JOIN lang_map m ON m.language=d.language JOIN lists src ON src.name=m.list_name JOIN subscriber_lists sl ON sl.list_id=src.id JOIN subscribers s ON s.id=sl.subscriber_id WHERE sl.status='confirmed' AND s.status='enabled' AND NOT EXISTS(SELECT 1 FROM bounces b WHERE b.subscriber_id=s.id) AND NOT EXISTS(SELECT 1 FROM subscriber_lists u WHERE u.subscriber_id=s.id AND u.status='unsubscribed');
DELETE FROM subscriber_lists sl USING lists l,lang_defs d WHERE sl.list_id=l.id AND l.name=d.group_name AND NOT EXISTS(SELECT 1 FROM eligible e WHERE e.language=d.language AND e.subscriber_id=sl.subscriber_id);
INSERT INTO subscriber_lists(subscriber_id,list_id,status) SELECT e.subscriber_id,l.id,'confirmed'::subscription_status FROM eligible e JOIN lang_defs d ON d.language=e.language JOIN lists l ON l.name=d.group_name ON CONFLICT(subscriber_id,list_id) DO NOTHING;
INSERT INTO campaigns(uuid,name,subject,from_email,body,content_type,status,type,messenger,template_id) SELECT gen_random_uuid(),d.campaign_name,d.subject,'Edward <edward.derma@consthruads.com>',d.body,'html','draft','regular','email',1 FROM lang_defs d WHERE NOT EXISTS(SELECT 1 FROM campaigns c WHERE c.name=d.campaign_name);
DO $$ BEGIN IF EXISTS(SELECT 1 FROM campaigns c JOIN lang_defs d ON d.campaign_name=c.name WHERE c.status<>'draft' OR c.sent<>0) THEN RAISE EXCEPTION 'Existing campaign is not an untouched draft'; END IF; END $$;
UPDATE campaigns c SET subject=d.subject,from_email='Edward <edward.derma@consthruads.com>',body=d.body,content_type='html',messenger='email',template_id=1,updated_at=now() FROM lang_defs d WHERE c.name=d.campaign_name AND c.status='draft' AND c.sent=0;
DELETE FROM campaign_lists cl USING campaigns c,lang_defs d WHERE cl.campaign_id=c.id AND c.name=d.campaign_name;
INSERT INTO campaign_lists(campaign_id,list_id) SELECT c.id,l.id FROM campaigns c JOIN lang_defs d ON d.campaign_name=c.name JOIN lists l ON l.name=d.group_name;
WITH stats AS (SELECT c.id,COUNT(DISTINCT s.id)::integer n,COALESCE(MAX(s.id),0)::integer max_id FROM campaigns c JOIN lang_defs d ON d.campaign_name=c.name JOIN campaign_lists cl ON cl.campaign_id=c.id JOIN subscriber_lists sl ON sl.list_id=cl.list_id JOIN subscribers s ON s.id=sl.subscriber_id WHERE sl.status='confirmed' AND s.status='enabled' AND NOT EXISTS(SELECT 1 FROM bounces b WHERE b.subscriber_id=s.id) GROUP BY c.id) UPDATE campaigns c SET to_send=stats.n,max_subscriber_id=stats.max_id,last_subscriber_id=0 FROM stats WHERE c.id=stats.id;
SELECT json_build_object('languages',(SELECT COUNT(*) FROM lang_defs),'mapped_countries',(SELECT COUNT(*) FROM lang_map),'audience_members',(SELECT json_object_agg(d.language,(SELECT COUNT(*) FROM subscriber_lists sl JOIN lists l ON l.id=sl.list_id WHERE l.name=d.group_name AND sl.status='confirmed')) FROM lang_defs d),'campaigns',(SELECT COUNT(*) FROM campaigns c JOIN lang_defs d ON d.campaign_name=c.name WHERE c.status='draft' AND c.sent=0),'total_targets',(SELECT SUM(c.to_send) FROM campaigns c JOIN lang_defs d ON d.campaign_name=c.name),'unsafe_members',(SELECT COUNT(*) FROM subscriber_lists sl JOIN lists l ON l.id=sl.list_id JOIN lang_defs d ON d.group_name=l.name JOIN subscribers s ON s.id=sl.subscriber_id WHERE s.status<>'enabled' OR EXISTS(SELECT 1 FROM bounces b WHERE b.subscriber_id=s.id))); COMMIT;'''

host=os.environ.get("VPS_HOST","187.127.70.251"); pw=os.environ["LISTMONK_VPS_PASSWORD"]
cli=paramiko.SSHClient(); cli.set_missing_host_key_policy(paramiko.AutoAddPolicy()); cli.connect(host,username="root",password=pw,timeout=20)
b64=base64.b64encode(sql.encode()).decode(); cmd=f'''docker exec listmonk-production-postgres-1 sh -lc 'echo {b64} | base64 -d | psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -At' '''
_,o,e=cli.exec_command(cmd,timeout=1200); out=o.read().decode(); err=e.read().decode(); cli.close()
if err.strip(): raise RuntimeError(err)
rows=[x for x in out.splitlines() if x.startswith("{")]; print(json.dumps(json.loads(rows[-1]),ensure_ascii=False,indent=2))
