#!/usr/bin/env python3
"""Replace dental no-repeat draft bodies with faithful localized copy."""
import base64, json, os
import paramiko

COPY = {
38: ("es", ["Estimado/a dentista:", "Estaba buscando clínicas dentales de la zona en Google Maps y encontré su clínica, así que pensé en ponerme en contacto con usted.", "Somos una empresa de desarrollo de software y esta es solo una presentación muy breve de dos soluciones que ofrecemos para clínicas dentales:", "Páginas web para clínicas dentales", "Renovamos la imagen o rediseñamos su página web actual para dar a su clínica una presencia online más moderna y profesional. La IA está cambiando las reglas del juego en el diseño web, y algunos de los nuevos diseños y posibilidades son absolutamente impresionantes.", "Software CRM para clínicas dentales", "Un sistema sencillo para gestionar las consultas de pacientes, los seguimientos y las citas en un solo lugar.", "Puede echar un vistazo rápido a ambas soluciones aquí:", "Si le parece relevante para su clínica, estaré encantado de mantener una breve conversación.", "Un cordial saludo"]),
39: ("en", ["Caro(a) Dentista,", "Estava a pesquisar clínicas dentárias na região através do Google Maps e encontrei a sua clínica, por isso decidi entrar em contacto.", "Somos uma empresa de desenvolvimento de software e esta é apenas uma breve apresentação de duas soluções que oferecemos para clínicas dentárias:", "Websites para Clínicas Dentárias", "Fazemos o rebranding ou redesenho do seu website atual para proporcionar à clínica uma presença online mais moderna e profissional. A IA está a mudar o web design, e alguns dos novos designs e possibilidades são absolutamente impressionantes.", "Software CRM para Clínicas Dentárias", "Um sistema simples para gerir pedidos de pacientes, acompanhamentos e consultas num único lugar.", "Pode conhecer rapidamente ambas as soluções aqui:", "Se considerar que pode ser relevante para a sua clínica, terei todo o gosto em conversar brevemente consigo.", "Com os melhores cumprimentos"]),
40: ("fr", ["Cher/Chère dentiste,", "En recherchant des cliniques dentaires dans la région sur Google Maps, j’ai découvert votre cabinet et j’ai donc souhaité vous contacter.", "Nous sommes une société de développement logiciel et voici une très brève présentation de deux solutions que nous proposons aux cliniques dentaires :", "Sites web pour cabinets dentaires", "Nous modernisons l’image ou repensons votre site actuel afin d’offrir à votre clinique une présence en ligne plus moderne et professionnelle. L’IA transforme la conception web, et certains des nouveaux designs et possibilités sont absolument remarquables.", "Logiciel CRM pour cabinets dentaires", "Un système simple pour gérer au même endroit les demandes des patients, les relances et les rendez-vous.", "Vous pouvez découvrir rapidement les deux solutions ici :", "Si cela vous semble pertinent pour votre clinique, je serais heureux d’échanger brièvement avec vous.", "Bien cordialement"]),
41: ("en", ["Gentile Dentista,", "Stavo cercando su Google Maps delle cliniche dentali nella zona e ho trovato il suo studio, perciò ho pensato di contattarla.", "Siamo una società di sviluppo software e questa è solo una breve presentazione di due soluzioni che offriamo alle cliniche dentali:", "Siti web per studi dentistici", "Rinnoviamo l’immagine o riprogettiamo il sito esistente per offrire alla clinica una presenza online più moderna e professionale. L’IA sta cambiando il mondo del web design e alcuni dei nuovi progetti e delle nuove possibilità sono davvero straordinari.", "Software CRM per studi dentistici", "Un sistema semplice per gestire in un unico luogo le richieste dei pazienti, i follow-up e gli appuntamenti.", "Può dare una rapida occhiata a entrambe le soluzioni qui:", "Se ritiene che possa essere utile per la sua clinica, sarò lieto di parlarne brevemente.", "Cordiali saluti"]),
42: ("en", ["Stimate medic stomatolog,", "Căutând clinici stomatologice din zonă pe Google Maps, am găsit cabinetul dumneavoastră și m-am gândit să vă contactez.", "Suntem o companie de dezvoltare software, iar aceasta este doar o prezentare foarte scurtă a două soluții pe care le oferim clinicilor stomatologice:", "Site-uri web pentru clinici stomatologice", "Modernizăm imaginea sau reproiectăm site-ul existent pentru a oferi clinicii o prezență online mai modernă și profesională. Inteligența artificială schimbă radical designul web, iar unele dintre noile proiecte și posibilități sunt absolut impresionante.", "Software CRM pentru clinici stomatologice", "Un sistem simplu pentru gestionarea solicitărilor pacienților, urmăririlor și programărilor într-un singur loc.", "Puteți vedea rapid ambele soluții aici:", "Dacă vi se pare relevant pentru clinică, aș discuta cu plăcere pe scurt.", "Cu stimă"]),
43: ("ru", ["Уважаемый стоматолог!", "Во время поиска стоматологических клиник в вашем районе на Google Maps я увидел вашу клинику и решил связаться с вами.", "Мы занимаемся разработкой программного обеспечения, и это лишь очень краткое представление двух решений, которые мы предлагаем стоматологическим клиникам:", "Сайты для стоматологических клиник", "Мы обновляем фирменный стиль или перерабатываем существующий сайт, чтобы обеспечить клинике более современное и профессиональное присутствие в интернете. Искусственный интеллект меняет веб-дизайн, и некоторые новые проекты и возможности действительно впечатляют.", "CRM для стоматологических клиник", "Простая система для управления обращениями пациентов, последующими контактами и записями на приём в одном месте.", "Кратко ознакомиться с обоими решениями можно здесь:", "Если это актуально для вашей клиники, буду рад коротко обсудить детали.", "С уважением"]),
}

def quote(s): return "'" + s.replace("'", "''") + "'"
def html(code, v):
    url=f"https://www.consthruads.com/dentist/?lang={code}"
    return f'''<p>{v[0]}</p>\n<p>{v[1]}</p>\n<p>{v[2]}</p>\n<p><strong>1. {v[3]}</strong> – {v[4]}</p>\n<p><strong>2. {v[5]}</strong> – {v[6]}</p>\n<p>{v[7]}<br>\n<a href="{url}" target="_blank" rel="noopener noreferrer">\n{url}\n</a>\n</p>\n<p>{v[8]}</p>\n<p>{v[9]},<br>\nEdward\n</p>'''

values=",".join(f"({cid},{quote(html(code,text))},{quote(code)})" for cid,(code,text) in COPY.items())
sql=f'''\\set ON_ERROR_STOP on
BEGIN;
CREATE TEMP TABLE fixes(id integer, body text, code text); INSERT INTO fixes VALUES {values};
DO $$ BEGIN IF (SELECT count(*) FROM campaigns c JOIN fixes f ON f.id=c.id WHERE c.status='draft' AND c.sent=0)<>6 THEN RAISE EXCEPTION 'All targets must be untouched drafts'; END IF; END $$;
UPDATE campaigns c SET body=f.body,content_type='html',updated_at=now() FROM fixes f WHERE c.id=f.id AND c.status='draft' AND c.sent=0;
SELECT json_agg(json_build_object('id',c.id,'status',c.status,'sent',c.sent,'targets',c.to_send,'code',f.code,'link_ok',position('dentist/?lang='||f.code in c.body)>0,'old_copy_removed',position('Patient Acquisition' in c.body)=0) ORDER BY c.id) FROM campaigns c JOIN fixes f ON f.id=c.id;
COMMIT;'''

c=paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy()); c.connect('187.127.70.251',username='root',password=os.environ['LISTMONK_VPS_PASSWORD'])
p=base64.b64encode(sql.encode()).decode(); cmd=f'''docker exec listmonk-production-postgres-1 sh -lc 'echo {p} | base64 -d | psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -At' '''
_,o,e=c.exec_command(cmd); out=o.read().decode(); err=e.read().decode(); c.close()
if err.strip(): raise RuntimeError(err)
print(out)
